<?php

// Tabela Básica IDs Forma de Pagamento
define("CONSTFORMAPAGAMENTOIDDINHEIRO", 1);
define("CONSTFORMAPAGAMENTOIDCARTAOCREDITO", 2);
define("CONSTFORMAPAGAMENTOIDCARTAODEBITO", 3);
define("CONSTFORMAPAGAMENTOIDCHEQUE", 4);
define("CONSTFORMAPAGAMENTOIDTRANSFERENCIA", 5);

// IDs Situação Agenda
define("situacaoAgendaLiberado", 1);
define("situacaoAgendaAgendado", 2);
define("situacaoAgendaAguardando", 3);
define("situacaoAgendaAtendimento", 4);
define("situacaoAgendaAtendido", 5);
define("situacaoAgendaCancelado", 6);

// SITUACAO CONTROLE DE REACAO DE APLICACAO VACINA
define("CONSTREACAOVACINAIDPENDENTE", 1);
define("CONSTREACAOVACINAIDREGISTRADO", 2);
define("CONSTREACAOVACINAIDFINALIDADO", 3);
define("CONSTREACAOVACINAIDCANCELADO", 4);

// SITUACAO CONTROLE DE PROXIMA DOSE APLICACAO VACINA
define("CONSTPROXDOSEVACINAIDPENDENTE", 1);
define("CONSTPROXDOSEVACINAIDREGISTRADO", 2);
define("CONSTPROXDOSEVACINAIDFINALIZADO", 3);
define("CONSTPROXDOSEVACINAIDCANCELADO", 4);
